[pytest]
addopts = -s -v
python_files = test_*.py
python_classes = Test*
python_functions = test_*

markers =
    ui : Маркировка для UI автотесты
    critical: Маркировка для критичных автотестов
    slow: Маркировка для медленных автотестов
    smoke: Маркировка для смоук автотестов
    regression: Маркировка для регрессионых автотестов
    registration: Маркировка для автотестов, связанных с регистрацией пользователя
    authorization: Маркировка для автотестов, связанных с авторизацией пользователя
    courses: Маркировка для автотестов, связанных с курсами
    dashboard: Маркмировка для автотестов, связанных с рабочей панелью